spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
        enable_lazy_load_no_trans: true
    show-sql: false
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true