server:
  port: ${SERVER_PORT:8092}
spring:
  application:
    name: montage-core
  datasource:
    password: ${DB_PASSWORD:1234}
    username: ${DB_USERNAME:postgres}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/montage_main}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${DB_SCHEMA:public}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    view:
      suffix: .html
      prefix: /view/
  profiles:
    include: >
      db,
      log
